import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api, RouterOutputs } from "~/utils/api";

export default function ProfilePage() {
  const { isLoaded: userLoaded } = useUser();

  api.posts.getAll.useQuery();
  // return empty div if user isn't loaded yet
  if (!userLoaded) return <div />;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full text-center h-full justify-center border-slate-600 md:max-w-2xl border-x">
         Profile Views
        </div>
      </main>
    </>
  );
}
