import { SignedIn, SignedOut, SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import { api, RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import Image from "next/image";

dayjs.extend(relativeTime)
const CreatePostWizard = () => {
  const {user} =  useUser();

  if (!user) return null;

  return <div className="flex gap-3">
    <Image 
      src={user.imageUrl} 
      alt="Profile Image" 
      className="rounded-full w-14 h-14" 
      width={56} 
      height={56} /> 
    <input placeholder="Type something!" className="bg-transparent outline-none grow"/>
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.authorId}  className="flex gap-3 p-4 border-b border-slate-400">
      <Image alt={`@${author.username}`} src={author.imageUrl} className="rounded-full h-14 w-14" width={56} height={56} />
      <div className="flex flex-col font-segoe">
        <div className="flex gap-1 text-gray-500">
          <span>{`@${author.username} `}</span>
          <span>{` · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {
  const { data: postsData, isSuccess } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full border-slate-400 md:max-w-2xl border-x">
          <div className="flex p-4 border-b border-slate-400">
            <div className="flex justify-center">
              <SignedOut>
                <SignInButton />
              </SignedOut>
            </div>
            <div className="flex justify-center">
              <SignedIn>
                <CreatePostWizard />
              </SignedIn>
            </div>
          </div>
        <div className="flex flex-col">
          {postsData?.map((fullPost) => (
            <PostView {...fullPost} key={fullPost.post.id} />))}
        </div>
        </div>
      </main>
    </>
  );
}
