import { SignedIn, SignedOut, SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api, RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import Image from "next/image";
import { LoadingPage, LoadingSpinner } from "~/components/loading";
import toast from "react-hot-toast";

dayjs.extend(relativeTime)
const CreatePostWizard = () => {
  const {user} =  useUser();

  const ctx = api.useUtils();

  const { mutate: createPost, isPending: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.invalidate();
    },
    onError: (e) => {
      const errorMessage = e.data?.zodError?.fieldErrors.content;
      if (Array.isArray(errorMessage) && errorMessage[0]) {
        toast.error(errorMessage[0]);
      } else {
        toast.error("Something went wrong while creating the post");
      }
    }
  });

  const [input, setInput] = useState<string>("");

  if (!user) return null;

  return <div className="flex justify-between w-full flex-row gap-3">
    <div className="flex flex-row gap-3">
    <Image 
      src={user.imageUrl} 
      alt="Profile Image" 
      className="rounded-full w-14 h-14" 
      width={56} 
      height={56} /> 
    <input 
      placeholder="Type something!" 
      className="bg-transparent outline-none grow"
      value={input}
      onChange={(e) => setInput(e.target.value)}
      disabled={isPosting}
      onKeyDown={(e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          if (input !== "") {
            createPost({ content: input });
          }
        }
      }}
      />
    </div>
    {input !== "" && !isPosting && (
      <button className="" onClick={() => createPost({ content: input })} disabled={isPosting}>Post</button>
      )}
    {isPosting && (
      <div className="flex justify-center items-center">
        <LoadingSpinner size={25}/>
      </div>
      )}
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.authorId}  className="flex gap-3 p-4 border-b border-slate-600">
      <Image alt={`@${author.username}`} src={author.imageUrl} className="rounded-full h-14 w-14" width={56} height={56} />
      <div className="flex flex-col font-segoe">
        <div className="flex gap-1 text-gray-500">
          <Link href={`/@${author.username}`}>
            <span>{`@${author.username} `}</span>
          </Link>
          <Link href={`/post/${post.id}`}>
            <span>{` · ${dayjs(post.createdAt).fromNow()}`}</span>
          </Link>
        </div>
        <span className="text-xl">{post.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data: postsData, isSuccess, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;

  if (!postsData) return <div>Something went wrong</div>

  return (
  <div className="flex flex-col">
    {postsData?.map((fullPost) => (
      <PostView {...fullPost} key={fullPost.post.id} />))}
  </div>
  )
}

export default function Home() {
  const { isLoaded: userLoaded } = useUser();

  api.posts.getAll.useQuery();
  // return empty div if user isn't loaded yet
  if (!userLoaded) return <div />;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full border-slate-600 md:max-w-2xl border-x">
          <div className="flex p-4 border-b border-slate-600">
            <div className="flex justify-center">
              <SignedOut>
                <SignInButton />
              </SignedOut>
            </div>
            <div className="flex justify-center w-full">
              <SignedIn>
                <CreatePostWizard />
              </SignedIn>
            </div>
          </div>
        <Feed />
        </div>
      </main>
    </>
  );
}
